/* eslint-disable no-var */
export var DEPRECATE_HAS_RECORD = true;
export var DEPRECATE_JSON_API_FALLBACK = true;
export var DEPRECATE_PROMISE_PROXIES = true;
export var DEPRECATE_STORE_FIND = true;
export var DEPRECATE_V1CACHE_STORE_APIS = true;
export var DEPRECATE_PROMISE_MANY_ARRAY_BEHAVIORS = true;
export var DEPRECATE_NON_EXPLICIT_POLYMORPHISM = true;
export var DEPRECATE_EARLY_STATIC = true;
export var DEPRECATE_MODEL_REOPEN = true;
export var DEPRECATE_SAVE_PROMISE_ACCESS = true;
export var DEPRECATE_RELATIONSHIPS_WITHOUT_ASYNC = true;
export var DEPRECATE_RELATIONSHIPS_WITHOUT_INVERSE = true;
export var DEPRECATE_RELATIONSHIPS_WITHOUT_TYPE = true;
export var DEPRECATE_RSVP_PROMISE = true;
export var DEPRECATE_SNAPSHOT_MODEL_CLASS_ACCESS = true;
export var DEPRECATE_A_USAGE = true;
export var DEPRECATE_ARRAY_LIKE = true;
export var DEPRECATE_V1_RECORD_DATA = true;
export var DEPRECATE_STRING_ARG_SCHEMAS = true;
export var DEPRECATE_HELPERS = true;
export var DEPRECATE_COMPUTED_CHAINS = true;

export var DEPRECATIONS = {
  DEPRECATE_HAS_RECORD,
  DEPRECATE_JSON_API_FALLBACK,
  DEPRECATE_PROMISE_PROXIES,
  DEPRECATE_STORE_FIND,
  DEPRECATE_V1CACHE_STORE_APIS,
  DEPRECATE_PROMISE_MANY_ARRAY_BEHAVIORS,
  DEPRECATE_NON_EXPLICIT_POLYMORPHISM,
  DEPRECATE_EARLY_STATIC,
  DEPRECATE_MODEL_REOPEN,
  DEPRECATE_SAVE_PROMISE_ACCESS,
  DEPRECATE_RELATIONSHIPS_WITHOUT_ASYNC,
  DEPRECATE_RELATIONSHIPS_WITHOUT_INVERSE,
  DEPRECATE_RELATIONSHIPS_WITHOUT_TYPE,
  DEPRECATE_RSVP_PROMISE,
  DEPRECATE_SNAPSHOT_MODEL_CLASS_ACCESS,
  DEPRECATE_A_USAGE,
  DEPRECATE_ARRAY_LIKE,
  DEPRECATE_V1_RECORD_DATA,
  DEPRECATE_STRING_ARG_SCHEMAS,
  DEPRECATE_HELPERS,
  DEPRECATE_COMPUTED_CHAINS,
};
